### ISSUE TITLE
Quorum 0 should auto change to 1 when adding first signer

### ISSUE THREAD

**Issue by zgrguric** [XRPL-Labs/multi-signature-issue-tracker#5]
And only when added first signer, in that case there is only 1 and only "1 Quorum" is possible.
![6E264182-E620-4364-9333-32D7816572B4](https://github.com/XRPL-Labs/multi-signature-issue-tracker/assets/108837406/f1bcc2ac-d50f-4ccd-84db-10131086f8db)

**Comment by KoenPaas** [comment]
We will not implement this, reason is that the user always needs to manually select the quorum.

It is possible to make it 0 but we won't as this is that is the safe option.
